class Img:
    def __init__(self):
        ...

    def read(self, path: pathlib.Path, target_size: Optional[Tuple[int, int]] = None):
        ...

    def clone(self):
        ...

    def draw_on(self, other_img: 'Img', x: int, y: int, alpha: float = 1.0):
        ...

    def resize(self, new_width: int, new_height: int):
        ...
